### ISSUE TITLE
mainline kernel?

### ISSUE THREAD

**Issue by dnr** [considerate/nixos-odroidhc4#1]
Thanks so much for this! I just got an HC4 and I'm trying to set it up with NixOS, and this is a huge help. I got your image to boot successfully (using the 4.9 kernel from hardkernel). Now I'm looking to get a recent kernel on it, and getting kind of stuck.

According to the odroid forums, people are successfully using recent kernels using this fork: https://github.com/tobetter/linux (apparently from a hardkernel employee, although it's not the official one). It looks like there are images using that kernel with Ubuntu, Armbian, and even Manjaro, so it should be possible to get it working with NixOS too.

I've successfully built that kernel on the HC4, but I can't get it to boot, either with petitboot or with u-boot from this sdcard image (booting while holding the button). With petitboot, it displays "wake_on_lan = ..." and then hangs. With u-boot, it seems to fail somehow and then tries pxe-booting instead.

I did notice that the u-boot built into this image is a recent one (2021.01) and people on the forums seem to be sticking with the 2015 version from hardkernel, even for booting recent kernels. It seems that there's a nix derivation for both in this repo, though only the recent one is used. (I'm going to try building the old one to see what happens.)

I'm fairly new to embedded stuff so I don't really understand what's going on here or where to start debugging things. If you (or anyone else) has any advice for getting a mainline kernel going in NixOS, I'd really appreciate it.

**Comment by dnr** [comment]
I got this working eventually. I'll try to post some code or make a PR soon, but in case anyone is curious, the main points are:
- The code in this repo sets up the sdcard image with a recent version of u-boot, but the boot.ini that it generates doesn't boot with that 2021 u-boot, or with the 2015 u-boot that's in the official hardkernel ubuntu images. It only boots with petitboot, which emulates u-boot scripts in some undocumented way.
- I eventually gave up on petitboot and wiped it from my board so that it would use u-boot from the sdcard.
- Booting with u-boot is sensitive to load addresses (for the kernel, initrd, and fdt), and I can't find any documentation on what the memory map looks like or what addresses are valid. The load addresses in boot.ini generated by this code did not work for me. It turns out that u-boot sets load addresses in its initial environment, which is a better starting point. With 2015 u-boot, it required overriding one of them (for reasons I never figured out), and with 2021 u-boot, the defaults worked without changes.
- I did use the kernel fork that I mentioned, though the differences from the real mainline are pretty minor and just support a few extra hardware bits that I'm not using. So it's possible that even a kernel built by nixos hydra would work (minus those hardware bits), though I didn't try this.
- [Maybe] When I was trying to use the 2015 u-boot, the default load addresses leave 32MB for the kernel, and a kernel built with arm64 defconfig is about 41MB, so I had to add a custom config to shrink it (moving the load address did not work). This may or may not be a problem with the 2021 u-boot, I forgot to write down its default load addresses, but I do remember they were different.
- The u-boot built by this repo actually requires a boot.scr, not a boot.ini. The difference is a header with a checksum, and it has to be produced by mkimage. There's probably some u-boot build option to change this but I didn't look.
- The scripts in u-boot's default environment care about the "bootable" bit in the partition table, and those were set wrong. This was surprising because I thought nothing cares about that anymore :(
- [Optional] u-boot has full support for ext4, so there's no need for a separate vfat partition. I set it up so that it reads all the required files out of the nix store, so system activation doesn't require copying anything.

**Comment by considerate** [comment]
@dnr Thank you for having a look at this!

I was personally not able to understand all the changes between the hardkernel fork of Linux and the mainline kernel. This is the reason for using the forked version here. I'd gladly accept a pull request that updates the kernel to a more mainline version.

As for the bootloader, there are a couple of issues with the 'Das U-Boot' bootloader:
- You cannot compile the firmware on the HC4 since the firmware is encrypted with a tool that only works on x86_64-linux
- It doesn't support multiple boot entries which means that the whole rollback feature of NixOS becomes harder to use

I asked a couple of months back on the [Odroid forums](https://forum.odroid.com/viewtopic.php?f=206&t=41775) and seems that petitboot should also be able to pick up boot entries from GRUB. However, I never got around to actually implementing it here. I do think that GRUB might be the better bootloader to use for NixOS on HC4, though.

**Comment by dnr** [comment]
Note that there are two "forks" from hardkernel: the official one https://github.com/hardkernel/linux is on 4.9, and the unofficial(?) one https://github.com/tobetter/linux is on 5.11. (I say unofficial(?) because it appears to be from a hardkernel employee who is participating on the forums but is under their personal github account.)

Petitboot sounds like a good idea in theory, but I found it impossible to figure out what it's actually doing. U-boot is arcane but at least there are docs and I could see what was happening. GRUB sounds great as well and I'd be curious to try it if you get it working.

As for boot menus: It seems like it would be possible to do a little scripting to allow, e.g. interrupting autoboot and then typing a command like "generation 12". Not as nice as a menu but usable. I'm planning to use the board headless so it wouldn't really help me though.

And the u-boot build: Thanks again for nixifying that build! It's a nice ideal to be able to change the u-boot version in the nixos config and have it rebuild and install to an sdcard. In practice, I'm never going to update it for the life of the board, so as long as I can build it once and `dd` it, I'm happy :slightly_smiling_face:

**Comment by considerate** [comment]
I'd like to move to the mainline kernel, the mesong12a dts is there and hopefully we only need to provide the defconfig / extraKernelConfig to get it working.

**Comment by erdnaxe** [comment]
Is it possible to boot https://hydra.nixos.org/job/nixos/release-21.05/nixos.sd_image_new_kernel.aarch64-linux on the Odroid HC4 if U-boot is added at the beginning (steps: https://nixos.wiki/wiki/NixOS_on_ARM/ODROID-HC4).
The only big regression I am seeing is that SATA is not working. `lspci` output is empty.

Right now I am running Armbian with their `5.10.57-meson64` kernel without any issue. I am going to buy another microSD and try to compare both kernel to understand why SATA is broken.

**Comment by considerate** [comment]
@erdnaxe I tried to use the mainline kernel 5.13 on the mainline-kernel branch but I’m unable to get it to boot. There are two issues:

1. Sometimes it errors with ramdisk is corrupted
2. When I get past the ramdisk issue it stops without any output over the UART when the booti command is run.

**Comment by erdnaxe** [comment]
I tried again last week with latest NixOS stable (22.05), and now it seems that everything works out of the box :)
Two other people from "NixOS on ARM" Matrix.org room also reported positive feedbacks.

This wiki page is updated with current situation: https://nixos.wiki/wiki/NixOS_on_ARM/ODROID-HC4

**Comment by considerate** [comment]
@erdnaxe Thank you for reporting this. I might deprecate this repository if I can successfully use the NixOS 22.05 installation as-is.

**Comment by considerate** [comment]
@erdnaxe There were a couple of tweaks that I had to apply to get it building so I'm not deprecating this repo just yet. However, I was able to get a system with the mainline uboot and Linux kernels now.
