### ISSUE TITLE
Please add a license to the repository

### ISSUE THREAD

**Issue by Patagonicus** [considerate/nixos-odroidhc4#8]
Hi!

I recently got hands on an HC4 and have started playing around with NixOS on it. I'd be willing to make some contributions to this repository (such as taking a stab at https://github.com/considerate/nixos-odroidhc4/issues/7), but that is only feasible for me if it's under certain permissive licenses, such as MIT or Apache.

Would you mind adding a license of your choosing to the repository? I'm assuming that you intent the repository to be open source software, but currently it's in an unclear position.

Cheers,
Philipp

**Comment by considerate** [comment]
Thank you for showing interest in this repository. I have now [licensed](https://github.com/considerate/nixos-odroidhc4/blob/5ab023038351acc7ab07426104b9730b770faeaf/LICENSE.md) the software under the BSD 3-clause license. I hope this is of satisfaction to you.

Regards,
Viktor

**Comment by Patagonicus** [comment]
Thanks! Yes, BSD 3-clause makes it easy for me to send patches.

Unfortunately I've had some trouble building the repository - I'll collect logs + system information when I have some time and open a separate issue for that.
